### ISSUE TITLE
Feature Request: Option to disable pop-up windows

### ISSUE THREAD

**Issue by mikebronner** [mk12/vscode-better-git-line-blame#10]
I find the pop-up windows extremely annoying when in inline mode. They always end up covering code up that is being worked on or reviewed. It would be great if there was a way to disable these?

**Comment by mk12** [comment]
Are you using the latest version (0.2.9)? And do you have the config "betterGitLineBlame.annotateWholeLine" set to false (the default)? When that option is true, it can indeed be annoying because it shows up if you hover anywhere on the line. However, when it’s false it will only show up when hovering on the inline annotation at the end of the line.

One option is to set "editor.hover.enabled" to false. This will disable all hover popups in VS Code, not just mine. (You can still view them with the keyboard shortcut, Cmd/Ctrl K + I.)

If it is just this extension’s hovers that are particularly annoying, I’m curious why - does your mouse cursor just always happen to be on top of the commit messages while you’re typing? Is it a lot of effort to move it away? Do hover messages for documentation (which pretty much all the language extensions do by default) also bother you?

I’m not opposed to adding an option to disable them but I’d like to understand more first.

**Comment by mikebronner** [comment]
Hi @mk12, thanks for the swift response!

- I am using the latest version.
- I do have the "whole line" setting set to false.
- I can't disable all popups, because I do want code peeking when I hover over classes, methods, and variables (but that's all I use the popups for)
- we do a lot of pair programming, and I move my mouse out of the way off to the right of the code when my partner is controlling my screen. This invariably throws the popup. Another instance is that I like to move my mouse to an empty line (not off to the right), which will also trigger the popup and cover up code we're working on, because the popup is on a slight delay
- I think it is this extension specifically, because I don't care about the additional details in the popup, and only want to see the reference inline.
- another option I would be happy with is having the details show in a popup if I click on the inline blame message

Thanks for your consideration! :)

**Comment by mk12** [comment]
That makes sense. I've added `betterGitLineBlame.enableHoverMessages` in 0.2.10. Let me know if that works!

**Comment by mk12** [comment]
(There was an issue publishing 0.2.10 so I had to make another. It should be available in 0.2.11 now.)
