### ISSUE TITLE
Undone changes stuck as "You - uncommited changes"

### ISSUE THREAD

**Issue by Tarpsvo** [mk12/vscode-better-git-line-blame#3]
Heya!

VSCode: 1.87.2 (Universal)
Extension: 0.2.3
OS: MacOS 13.6

When I change a line and then undo the changes, the lines affected (and sometimes some random lines surrounding it) it will be stuck as "You - uncommited changes".

![image](https://github.com/mk12/vscode-better-git-line-blame/assets/2018660/f320af5f-f4a0-4569-afa7-fb14b8adc715)

**Comment by mk12** [comment]
Yeah, that's a tradeoff I made with the current implementation — see [Do I need to reblame?](https://github.com/mk12/vscode-better-git-line-blame?tab=readme-ov-file#do-i-need-to-reblame) in the README. You can fix it by running the "Better Git Line Blame: Reblame File" command, or enabling the configuration "betterGitLineBlame.reblameOnSave" to do it automatically on save.

I wanted to avoid wastefully running `git blame` all the time like other extensions do. Maybe I should make that config true by default, since once per save is not that bad compared to once per movement/keystroke.

**Comment by Tarpsvo** [comment]
Oh, sorry about that! Didn't think to look for it in the README. Once per save is an okay trade off for me, so I'll just enable the option.
