### ISSUE TITLE
Wrong uncommited changes

### ISSUE THREAD

**Issue by lucasm** [mk12/vscode-better-git-line-blame#8]
When you change a line but revert to original state (unchanged) the Diff extension shows like you have uncommitted changes on this line.

Print:
![2024-08-07](https://github.com/user-attachments/assets/de6601a3-cc97-4fbe-98e7-422129a219d6)

**Comment by mk12** [comment]
Same as #3. Please see the [FAQ entry on this](https://github.com/mk12/vscode-better-git-line-blame?tab=readme-ov-file#do-i-need-to-reblame).

**Comment by mk12** [comment]
That said, if you can think of a good way of improving it I'm open to ideas. I should probably just make reblame on save the default since this has come up a few times (though people still might think it's a bug that it's wrong until saving).

One option would be to periodically do a diff (presumably much cheaper than blame) and trigger a reblame is the diff's set of changed lines is different from our set of "Uncommitted changes" lines. Would be nice if we could access whatever underlies VS Code's diff info in the gutter instead of calling git diff ourselves, but not sure there is a way.
